remote_theme: pages-themes/time-machine@v0.2.0

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Sanket Ghadge

Description: Cybersecurity enthusiast passionate about ethical hacking, network defense, and Python development. Turning security threats into learning opportunities and technology into safer systems.
